### ISSUE TITLE
[ruby] Installing grpc gem fails to build native extension

### ISSUE THREAD

**Issue by marcinwyszynski** [grpc/grpc-common#267] opened 2015-07-23 16:43 UTC
```
marcinw@bruno:~/Code/fortune_services$ gem install grpc
Building native extensions.  This could take a while...
ERROR:  Error installing grpc:
        ERROR: Failed to build gem native extension.

    /Users/marcinw/.rvm/rubies/ruby-2.1.5/bin/ruby -r ./siteconf20150723-81112-at8lgb.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling rb_byte_buffer.c
compiling rb_call.c
rb_call.c:134:66: error: missing field 'reserved' initializer [-Werror,-Wmissing-field-initializers]
    {GRPC_RB_GC_NOT_MARKED, GRPC_RB_GC_DONT_FREE, md_ary_datasize},
                                                                 ^
rb_call.c:142:78: error: missing field 'reserved' initializer [-Werror,-Wmissing-field-initializers]
    {GRPC_RB_GC_NOT_MARKED, grpc_rb_call_destroy, GRPC_RB_MEMSIZE_UNAVAILABLE},
                                                                             ^
rb_call.c:274:50: error: unused parameter 'key' [-Werror,-Wunused-parameter]
static int grpc_rb_md_ary_capacity_hash_cb(VALUE key, VALUE val,
                                                 ^
rb_call.c:349:64: error: unused parameter 'val' [-Werror,-Wunused-parameter]
static int grpc_rb_call_check_op_keys_hash_cb(VALUE key, VALUE val,
                                                               ^
4 errors generated.
make: *** [rb_call.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/marcinw/.rvm/gems/ruby-2.1.5/gems/grpc-0.10.0 for inspection.
Results logged to /Users/marcinw/.rvm/gems/ruby-2.1.5/extensions/x86_64-darwin-14/2.1.0-static/grpc-0.10.0/gem_make.out
```

**Comment by murgatroid99** [comment] 2015-07-23 16:56
This was fixed in grpc/grpc#2476, but the fix has not yet been published.

**Comment by marcinwyszynski** [comment] 2015-07-23 16:59
@murgatroid99 Interestingly I get something similar for each version of this gem :(

**Comment by marcinwyszynski** [comment] 2015-07-23 17:05
Also, it's unfortunately still failing at HEAD:

```
marcinw@bruno:~/Downloads/grpc/src/ruby$ gem build grpc.gemspec
WARNING:  bin/math.rb is missing #! line
WARNING:  bin/math_services.rb is missing #! line
WARNING:  prerelease dependency on google-protobuf (~> 3.0.0alpha.1.1) is not recommended
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: grpc
  Version: 0.10.0
  File: grpc-0.10.0.gem
marcinw@bruno:~/Downloads/grpc/src/ruby$ gem install grpc-0.10.0.gem
Building native extensions.  This could take a while...
ERROR:  Error installing grpc-0.10.0.gem:
        ERROR: Failed to build gem native extension.

    /Users/marcinw/.rvm/rubies/ruby-2.2.0/bin/ruby -r ./siteconf20150723-84018-1gw0ck1.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling rb_byte_buffer.c
compiling rb_call.c
rb_call.c:247:20: error: implicit conversion loses integer precision: 'long' to 'int' [-Werror,-Wshorten-64-to-32]
    array_length = RARRAY_LEN(val);
                 ~ ^~~~~~~~~~~~~~~
/Users/marcinw/.rvm/rubies/ruby-2.2.0/include/ruby-2.2.0/ruby/ruby.h:900:6: note: expanded from macro 'RARRAY_LEN'
     (long)((RBASIC(a)->flags >> RARRAY_EMBED_LEN_SHIFT) & \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rb_call.c:247:20: error: implicit conversion loses integer precision: 'long' to 'int' [-Werror,-Wshorten-64-to-32]
    array_length = RARRAY_LEN(val);
                 ~ ^~~~~~~~~~~~~~~
/Users/marcinw/.rvm/rubies/ruby-2.2.0/include/ruby-2.2.0/ruby/ruby.h:902:25: note: expanded from macro 'RARRAY_LEN'
     RARRAY(a)->as.heap.len)
     ~~~~~~~~~~~~~~~~~~~^~~
2 errors generated.
make: *** [rb_call.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/marcinw/.rvm/gems/ruby-2.2.0/gems/grpc-0.10.0 for inspection.
Results logged to /Users/marcinw/.rvm/gems/ruby-2.2.0/extensions/x86_64-darwin-14/2.2.0/grpc-0.10.0/gem_make.out
```

**Comment by murgatroid99** [comment] 2015-07-23 18:04
I can't reproduce that error at HEAD on Mac or Linux. This seems like it might be something particular to your compiler. What compiler are you using? I don't think any compiler we test with checks for integer conversion problems with the warning flags we pass.

**Comment by marcinwyszynski** [comment] 2015-07-23 18:06
Thanks for looking into that!

```
marcinw@bruno:~/Downloads/grpc/src/ruby$ gcc --version
gcc-4.9 (Homebrew gcc 4.9.1) 4.9.1
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
gcc-4.9 (Homebrew gcc 4.9.1) 4.9.1
```

I submitted a PR with a path at https://github.com/grpc/grpc/pull/2632

**Comment by louiscryan** [comment] 2015-09-03 22:06
@tbetbetbe The PR has been merged, can you close if this is resolved?

**Closed** 2016-09-08 23:05 UTC
