### ISSUE TITLE
cpp route_guide server does not service multiple connections at once

### ISSUE THREAD

**Issue by larsonmpdx** [grpc/grpc-common#199] opened 2015-05-13 22:29 UTC
I compiled grpc from git 0fff02c (13 may 2015) and used grpc-common git d03233e (7 may 2015)

compiled on gcc 4.8.2 targeting x86_64 (linux)

when I run route_guide_server and connect with route_guide_client it works fine.  it takes 10 seconds to run because of the random delays put into RecordRoute() (this is normal).  Before it finishes, if I launch a second route_guide_client, client 2 doesn't execute any calls until client 1 finishes.  Client 2 starts immediately after 1 finishes so it seems like it's already connected but just waiting on something.

**Comment by yang-g** [comment] 2015-05-14 07:06
I cannot reproduce it on my local machine with an up-to-date grpc and grpc-common code. The two clients run fine. Could you double check whether the problem exists after syncing up the code?

**Comment by larsonmpdx** [comment] 2015-05-14 14:59
thank you for checking, I am looking into this on a fresh install

**Comment by larsonmpdx** [comment] 2015-05-14 15:44
I get the same behavior on AWS debian with gcc 4.7.2 and a fresh install of an ubuntu 14.04 VM (what I was using before) with a pull from this morning.  client 2 runs correctly but hangs at its first RPC until client 1 is finished.  I wonder if it's some IP problem when running two clients and a server on the same machine?  What's your local setup? I can try to replicate that

**Comment by larsonmpdx** [comment] 2015-05-14 18:44
I got a simplified server building in vs2013 and it works correctly, requests from many clients are interleaved.  I'm going to try debian 8 next

**Comment by larsonmpdx** [comment] 2015-05-14 20:21
ok, same story in debian 8.  here's a screenshot, client 1 on the left starts and sends a message with 1s delays.  the server is set to echo the messages back.  client 2 on the right does the same thing, and is able to send messages but gets no replies until client 1 finishes (after 6 seconds).  then it gets its backlog and is interactive as it should be

![image](https://cloud.githubusercontent.com/assets/12436438/7641027/f9bc2594-fa3b-11e4-8edb-85b0ad98f86a.png)

**Comment by yang-g** [comment] 2015-05-14 20:53
Was the experiment on a vm? How many cpus did the vm have?

**Comment by larsonmpdx** [comment] 2015-05-14 20:55
yes - 1

**Comment by larsonmpdx** [comment] 2015-05-14 20:59
ok, you got it, I changed # of cores to 2 and it can now service 2 clients, the third hangs

**Comment by yang-g** [comment] 2015-05-14 21:06
Yes I think the reason is because the server only has one thread. We use
the number of cpus as the default thread pool size. See
https://github.com/grpc/grpc/blob/master/src/cpp/server/server_builder.cc#L91
. You can increase "cores" to solve the issue too.

**Comment by yang-g** [comment] 2015-05-14 21:10
I am closing this since we seem to understand the cause.

**Comment by larsonmpdx** [comment] 2015-05-14 21:10
thanks for figuring this out.  are you planning on adding another threading model to support spawning new threads as clients connect (like thrift's TThreadedServer)?

**Closed by yang-g** 2015-05-14 21:10 UTC

**Comment by nicolasnoble** [comment] 2015-05-14 21:11
There was some talks about dynamic thread pools, yes. Nothing concrete yet however.
